# cloudbuild.yaml
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cashflow-api:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cashflow-api:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cashflow-api'
      - '--image=gcr.io/$PROJECT_ID/cashflow-api:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--timeout=300'
      - '--max-instances=10'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--port=8080'
      - '--concurrency=80'
      - '--set-env-vars=MONGODB_URI=${_MONGODB_URI},JWT_SECRET=${_JWT_SECRET},JWT_EXPIRE=${_JWT_EXPIRE},NODE_ENV=production'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/cashflow-api:$COMMIT_SHA'

substitutions:
  _MONGODB_URI:
  _JWT_SECRET:
  _JWT_EXPIRE: '30d'

options:
  logging: CLOUD_LOGGING_ONLY
